config/routes.rb
Rails.application.routes.draw do
  
  get '/search' => 'movie#search'

  resources :movie, only: [:index, :new, :create, :show, :edit, :update]

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base

# do some valisate the use input.
	validates :title, presence: true
	# validates :year_released, numericality: { greater_than: 2015 }

	# def self.search(query)
	# 	if query
	# 		@movie = Movie.where('title LIKE :search', { search: "%#{query}%"})
	# 	else
	# 		@movie = Movie.all
	# 		#params[:q]
	# 	end
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
	def index
		@movies = Movie.all()
	end

	def show
		@movie = Movie.find(params[:id])
		
	end

	def new

	end

	def create
		# Q1. How can the program can get the user input ??? done!!
		# render plain: params[:movie].inspect
		# Q2. How to create a Movie instance? 
		@movie = Movie.create()
		@movie.title = params[:movie][:title]
		@movie.description = params[:movie][:description]
		@movie.year_released = params[:movie][:year_released].to_i

		# Q3. How to save the new instant to db? 
		@movie.save
		# Q4. Where to go after success or failed? 

		redirect_to movie_index_path
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		@movie = Movie.find(params[:id])

		@movie.title = params[:movie][:title]
		@movie.description = params[:movie][:description]
		@movie.year_released = params[:movie][:year_released].to_i
		@movie.save
		# redirect_to movie_index_path
		redirect_to movie_index_path
  	end

	def search 
		
		
		@movies = Movie.where({title:params[:id]})
		#@movie.title = Movie.find(params[:movie][:title])
		#@movie.title = params[:movie][:title]
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>

<%= yield %>

</body>
</html>

app/views/movie/edit.html.erb
<h1>Go ahead an edit what you want!</h1>

<%= @movie.title %>


<%= form_for @movie do |f| %> 
<!-- movie_path = 'movie/:id' go to action "update"-->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :year_released %><br>
    <%= f.number_field :year_released %>
  </p>

  <p>
    <%= f.submit "Update Movie"%>
  </p>
<% end %>

app/views/movie/index.html.erb
<h1>Welcome to the movie app!</h1>
<p>See our collection of movies below or use our Search!</p>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:id, "Search for:") %>
  <%= text_field_tag(:id) %>
  <%= submit_tag("Search") %>
<% end %>

<ul>
<%
  @movies.each do |x|
%>
<li>
  <%= link_to x.title, x %> | <%= x.year_released%> | <%= link_to "Edit", edit_movie_path(x)%>
  <!-- link to "link name", "movie/index" -->
  <!-- link to "link name", movie_index_path -->
  <!-- link to "link name", object -->
</li>
<%    
  end
%>
</ul>

<%= link_to "Add New Movie", "/movie/new" %>

app/views/movie/new.html.erb
<h2>New Movie</h2>

<%= form_for :movie, url: movie_index_path do |f| %> 
<!-- movie_index_path = 'movie/' to action "create" -->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.label :year_released %><br>
    <%= f.number_field :year_released %>
  </p>

  <p>
    <%= f.submit "Create Movie"%>
  </p>
<% end %>

app/views/movie/search.html.erb
<h1>Your Search Results</h1>
<!-- studey the below.  from array into  -->
<% @movies.each do |movie| %> 

	<p>Title: <%= movie.title %></p>

	<p>Description: <%= movie.description %></p>

	<p>Year: <%= movie.year_released %></p>

	<%= link_to "Back", movie_index_path %>
	<%= link_to "Edit", "/movie/edit" %>

<% end %>

app/views/movie/show.html.erb
<h2>Movie Information</h2>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:id, "Search for:") %>
  <%= text_field_tag(:id) %>
  <%= submit_tag("Search") %>
<% end %>



<p>Title: <%= @movie.title %></p>

<p>Description: <%= @movie.description %></p>

<p>Year: <%= @movie.year_released %></p>

<%= link_to "Back", movie_index_path %>
<%= link_to "Edit", "/movie/#{@movie.id}/edit/" %>